# Generated by Django 2.2.6 on 2019-12-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussystem',
            name='qty',
            field=models.FloatField(),
        ),
    ]
